FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache \
    python3 \
    make \
    g++ \
    libc6-compat

COPY package*.json ./
RUN npm install

# On ne copie pas les fichiers ici car ils seront montés via le volume
# On ne fait pas non plus le build car on utilise le mode dev

EXPOSE 3000

CMD ["npm", "run", "dev"] 